# Generated by Django 4.2.13 on 2026-07-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0005_llmconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='cache_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='estimated_cost_usd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='latency_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='model_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
