# Generated by Django 6.0.7 on 2026-08-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0006_chatmessage_cache_hit_chatmessage_estimated_cost_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='groq_api_key',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
